name: Auto Fetch Go Repos and Add Modules

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:      # Allows manual triggering

jobs:
  fetch-and-add-modules:
    runs-on: ubuntu-latest
    if: github.repository == 'khulnasoft/go.khulnasoft.com' # only run for main repo

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Go environment
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Fetch Go Repositories
      id: fetch_go_repos
      run: |
        org_name="khulnasoft-lab"  # Replace with your organization name
        repos=$(curl -s -H "Authorization: token ${{ secrets.ORG_REPO_TOKEN }}" \
        "https://api.github.com/orgs/$org_name/repos?per_page=100" | jq -r '.[] | select(.language == "Go") | .name')
        
        echo "Found Go repositories: $repos"
        echo "::set-output name=repos::$repos"

    - name: Make gen.sh executable
      run: chmod +x ./gen.sh

    - name: Add Go Modules
      run: |
        # Check if repositories.txt exists
        if [ ! -f repositories.txt ]; then
          echo "repositories.txt file not found!"
          exit 1
        fi
    
        # Read repository names from repositories.txt
        repos=$(<repositories.txt)
    
        if [ -z "$repos" ]; then
          echo "No Go repositories found"
          exit 0
        fi
    
        for repo in $repos; do
          echo "Processing repository: $repo"
          ./gen.sh "$repo"
        done

    - name: Push changes
      run: |
        git config --global user.email "info@khulnasoft.com"
        git config --global user.name "GitHub Action"
        
        # Add changes
        git add .
    
        # Check for changes and commit if there are any
        if [ "$(git diff --cached --name-only)" ]; then
            git commit -m "Auto add Go modules for org repos"
            git push
        else
            echo "No changes to commit."
        fi
